parameters:
#    library_manager.example.class: Library\ManagerBundle\Example

services:
#    library_manager.example:
#        class: %library_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
