parameters:
#    library_curl.example.class: Library\CurlBundle\Example

services:
#    library_curl.example:
#        class: %library_curl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
