ServerCodeSearchBundle:
    resource: "@ServerCodeSearchBundle/Resources/config/routing.yml"
    prefix:   /

ServiceGoogleCodeBundle:
    resource: "@ServiceGoogleCodeBundle/Resources/config/routing.yml"
    prefix:   /

ServiceKodersBundle:
    resource: "@ServiceKodersBundle/Resources/config/routing.yml"
    prefix:   /

ServiceGithubBundle:
    resource: "@ServiceGithubBundle/Resources/config/routing.yml"
    prefix:   /

#CodeSearchBundle:
#    resource: "@CodeSearchBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
