parameters:
#    service_koders.example.class: Service\KodersBundle\Example

services:
#    service_koders.example:
#        class: %service_koders.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
